### ISSUE TITLE
Filter out junk rows

### ISSUE THREAD

**Issue by CaledoniaProject** [mazen160/server-status_PWN#1]
It seems like junk rows are not filtered

```
%> python server-status_PWN.py -u http://cyclelogistics.eu/server-status
...
[#] Requesting.
[New URL]:  http://?
[New Client]: ?
```

**Comment by mazen160** [comment]
I have tested this one, it looks like the provided website uses some sort of WAF in the back-end to block server-status_PWN.

It doesn't seem that there is something I have to do on this one, if you have any ideas to improve the tool, please let me know.

Thanks,
Mazin
