### ISSUE TITLE
Retrieving incorrect Data

### ISSUE THREAD

**Issue by dsn-hanno** [mazen160/server-status_PWN#2]
Hi guys,

i have recently used your program on a server status. The server status however, was giving all possible information and contained of numerous tables, with ssl statistics and such.

Running server-status_PWN on it, resulted in results similar to: https://github.com/mazen160/server-status_PWN/issues/1

However, instead of having Questionmarks, i just got some numbers. For Example: [New URL]:  http://27

Having looked at the code, i found the line of code causing this issue:

In Function: parse_response(self, response)  , you can find the Comment: URL-related.

The Variable table_index_id is the one you are looking for. Originally set to 0, i had to increase it, to eventually point to the right table.

I suggest adding this to the Readme for further Problems related to this and furthermore even allowing the user to determine this variable as a parameter at the start of the program.

Hope this helps!

**Comment by mazen160** [comment]
Hi @dsn-hanno,

Thank you for reporting this issue. I have updated the README to refer to the ticket for further details.
https://github.com/mazen160/server-status_PWN/commit/72aff5c080c0497890f829148228e369dd844ec2

Thanks,
Mazin
